#ifndef CONF_H
#define CONF_H

#define MAP_FILE "assets/map.txt"
#define MAX_PLAYERS 4
#define MAX_BEASTS 20
#define TIME_PER_TURN 500.0
#define PORT 8080
#define MAP_CHUNK_HEIGHT 5
#define MAP_CHUNK_WIDTH 5
#define INTERFACE_OFFSET_X 3
#define INTERFACE_OFFSET_Y 1
#define INTERFACE_HEIGHT 27
#define INTERFACE_WIDTH 105
#define SIDEBAR_OFFSET_X 49
#define SIDEBAR_OFFSET_Y 2
#define COIN_CASH 1
#define TREASURE_CASH 10
#define LARGE_TREASURE_CASH 25

#endif //CONF_H
